project:
  type: book

book:
  title: "welcome booklet"
  author: "PROVitD team"
  date: "today"
  chapters:
    - index.qmd
    - part: "Good practice"
      chapters:
        - good_practice/raw_data.qmd
        - good_practice/organize_analysis.qmd
    - part: "R tips"
      chapters:
        - R/R_projects.qmd
        - R/renv.qmd
    - part: "Bioinformatics ressources"
      chapters:
        - ressources/singlecell.qmd
        - ressources/workshop-training.qmd
        - ressources/cheatsheets.qmd
  repo-actions: [edit, issue]
  repo-url: https://github.com/provitd/welcome
  repo-branch: main

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrreprt